name: URL Usage Examples

on: push

jobs:
  deploy_to_subdomain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate URL-safe slugs
        uses: rlespinasse/github-slug-action@v5

      - name: Deploy to subdomain environment
        run: |
          ./deploy-application.sh --url "https://${{ env.GITHUB_REF_SLUG_URL }}.staging.app.example.com"

  deploy_to_path:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate URL-safe slugs
        uses: rlespinasse/github-slug-action@v5

      - name: Deploy to path-based environment
        run: |
          ./deploy-application.sh --url "https://staging.app.example.com/${{ env.GITHUB_REF_SLUG_URL }}"
